server:
  port: 0 # port 임의 지정
spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_order
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  # Eureka 서버에 아래 application.name으로 서비스명을 등록
  application:
    name: member-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

jwt:
  expiration: 30 # 30분
  secretKey: mySecret
